import type { TheoryQuestion } from './interviewTypes';

export const theoryQuestions: TheoryQuestion[] = [
  // ===== Fundamentos / Lógica =====
  {
    id: 'th-01',
    track: ['frontend', 'backend', 'fullstack'],
    level: ['junior', 'pleno', 'senior'],
    prompt: 'Qual a complexidade de tempo de uma busca binária em uma lista ordenada de n elementos?',
    options: ['O(n)', 'O(n²)', 'O(log n)', 'O(1)'],
    correctIndex: 2,
    explanation: 'Busca binária descarta metade do espaço de busca a cada comparação, resultando em complexidade logarítmica.',
  },
  {
    id: 'th-02',
    track: ['frontend', 'backend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Qual estrutura de dados é mais adequada para implementar um histórico de "desfazer" (Ctrl+Z)?',
    options: ['Fila (queue)', 'Pilha (stack)', 'Árvore binária', 'Tabela hash'],
    correctIndex: 1,
    explanation: 'Pilha é LIFO — o último estado salvo é o primeiro a ser desfeito, exatamente o comportamento esperado de undo.',
  },
  {
    id: 'th-03',
    track: ['frontend', 'backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Entre DFS (busca em profundidade) e BFS (busca em largura), qual garante encontrar o caminho mais curto em um grafo não-ponderado?',
    options: ['DFS', 'BFS', 'Ambos garantem igualmente', 'Nenhum dos dois'],
    correctIndex: 1,
    explanation: 'BFS explora todos os vizinhos do nível atual antes de avançar, garantindo que o primeiro caminho encontrado até o destino seja o mais curto em número de arestas.',
  },
  // ===== JavaScript / TypeScript =====
  {
    id: 'th-04',
    track: ['frontend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'O que `Object.freeze(obj)` faz exatamente?',
    options: [
      'Impede qualquer modificação no objeto, incluindo objetos aninhados',
      'Impede adicionar/remover/alterar propriedades de primeiro nível do objeto, mas não congela objetos aninhados',
      'Faz uma cópia profunda do objeto',
      'Bloqueia o objeto até um setTimeout terminar',
    ],
    correctIndex: 1,
    explanation: '`Object.freeze` é um congelamento superficial (shallow) — propriedades aninhadas (objetos dentro do objeto) continuam mutáveis.',
  },
  {
    id: 'th-05',
    track: ['frontend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Qual a diferença entre `interface` e `type` no TypeScript que mais importa na prática?',
    options: [
      'Não há diferença real, são sinônimos completos',
      'interface pode ser estendida (declaration merging) e é geralmente preferida para formas de objeto; type é mais flexível para unions e tipos primitivos',
      'type só funciona em arquivos .tsx',
      'interface não suporta métodos opcionais',
    ],
    correctIndex: 1,
    explanation: 'interfaces suportam merge de declarações (útil para extending de bibliotecas), enquanto type é necessário para unions, intersections e tipos mais complexos.',
  },
  {
    id: 'th-06',
    track: ['frontend', 'fullstack'],
    level: ['junior', 'pleno', 'senior'],
    prompt: 'O que esse código imprime?',
    code: 'console.log(0.1 + 0.2 === 0.3);',
    options: ['true', 'false', 'undefined', 'Erro de sintaxe'],
    correctIndex: 1,
    explanation: 'Por imprecisão de ponto flutuante, 0.1 + 0.2 resulta em 0.30000000000000004, não exatamente 0.3.',
  },
  {
    id: 'th-07',
    track: ['frontend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Em uma Promise.all([p1, p2, p3]), o que acontece se p2 for rejeitada enquanto p1 e p3 ainda estão pendentes?',
    options: [
      'Promise.all espera todas terminarem antes de rejeitar',
      'Promise.all rejeita imediatamente com o erro de p2, sem esperar p1/p3',
      'Promise.all ignora a rejeição de p2 e continua normalmente',
      'Promise.all trava indefinidamente',
    ],
    correctIndex: 1,
    explanation: 'Promise.all rejeita assim que qualquer uma das promises rejeita, não esperando as demais — para esperar todas independente do resultado, usa-se Promise.allSettled.',
  },
  // ===== React =====
  {
    id: 'th-08',
    track: ['frontend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Por que usar uma `key` estável (como um id) em listas renderizadas com .map() no React?',
    options: [
      'É só uma boa prática estética, sem efeito real',
      'Ajuda o React a identificar quais itens mudaram, foram adicionados ou removidos entre renders, evitando bugs visuais e re-renders desnecessários',
      'A key define a ordem visual dos itens',
      'Sem key, o React lança um erro fatal',
    ],
    correctIndex: 1,
    explanation: 'A key permite ao React reconciliar a lista corretamente. Usar o índice do array como key (em vez de um id estável) pode causar bugs sutis quando a lista é reordenada ou filtrada.',
  },
  {
    id: 'th-09',
    track: ['frontend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Qual o propósito principal dos Server Components no Next.js App Router?',
    options: [
      'Substituir completamente o CSS',
      'Renderizar no servidor sem enviar o JavaScript daquele componente ao navegador, reduzindo o bundle',
      'Acelerar apenas chamadas de banco de dados',
      'Funcionam só em modo de desenvolvimento',
    ],
    correctIndex: 1,
    explanation: 'Server Components rodam exclusivamente no servidor — o navegador recebe só o HTML resultante, sem precisar baixar o código JS daquele componente.',
  },
  {
    id: 'th-10',
    track: ['frontend', 'fullstack'],
    level: ['senior'],
    prompt: 'Por que abusar de useMemo/useCallback em todo componente pode não trazer o benefício esperado?',
    options: [
      'Eles sempre quebram a aplicação',
      'A própria memoização tem custo de memória/comparação, e usá-la sem necessidade real pode adicionar complexidade sem ganho de performance perceptível',
      'Eles foram descontinuados nas versões recentes do React',
      'Funcionam só dentro de useEffect',
    ],
    correctIndex: 1,
    explanation: 'Otimização prematura com memoização tem custo próprio. O ideal é medir antes de otimizar, aplicando memoização onde há um problema de performance real e mensurável.',
  },
  // ===== Backend / Node =====
  {
    id: 'th-11',
    track: ['backend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Qual status HTTP é apropriado quando um recurso é criado com sucesso via POST?',
    options: ['200', '201', '204', '202'],
    correctIndex: 1,
    explanation: '201 Created indica que a requisição resultou na criação de um novo recurso, geralmente retornando a localização/dados desse recurso.',
  },
  {
    id: 'th-12',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Qual a principal vantagem de usar injeção de dependência (DI) em vez de instanciar dependências com "new" diretamente?',
    options: [
      'O código roda mais rápido automaticamente',
      'Facilita substituir a implementação real por um mock em testes, e desacopla a classe de uma implementação específica',
      'É a única forma suportada pela linguagem',
      'Elimina completamente a necessidade de testes',
    ],
    correctIndex: 1,
    explanation: 'DI inverte o controle de criação de dependências, permitindo testar uma classe isoladamente substituindo dependências reais por mocks, sem mudar o código da classe.',
  },
  {
    id: 'th-13',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'O que caracteriza uma operação idempotente numa API?',
    options: [
      'Ela sempre retorna o mesmo tempo de resposta',
      'Executá-la múltiplas vezes produz o mesmo resultado final que executá-la uma única vez',
      'Ela nunca pode falhar',
      'Ela só pode ser usada com o verbo GET',
    ],
    correctIndex: 1,
    explanation: 'Idempotência significa que repetir a operação não muda o resultado final — importante para lidar com retries seguros em sistemas distribuídos.',
  },
  {
    id: 'th-14',
    track: ['backend', 'fullstack'],
    level: ['senior'],
    prompt: 'Em uma arquitetura de microsserviços, qual o papel de um Circuit Breaker?',
    options: [
      'Acelerar todas as chamadas entre serviços',
      'Parar de enviar requisições para um serviço que está falhando repetidamente, evitando sobrecarga em cascata',
      'Substituir a necessidade de testes de integração',
      'Criptografar a comunicação entre serviços',
    ],
    correctIndex: 1,
    explanation: 'Circuit Breaker detecta falhas repetidas num serviço dependente e "abre o circuito", falhando rápido em vez de esperar, protegendo o sistema de uma falha em cascata.',
  },
  // ===== Banco de dados =====
  {
    id: 'th-15',
    track: ['backend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Qual JOIN retorna todas as linhas da tabela à esquerda, mesmo sem correspondência na tabela à direita?',
    options: ['INNER JOIN', 'LEFT JOIN', 'CROSS JOIN', 'Nenhum JOIN faz isso'],
    correctIndex: 1,
    explanation: 'LEFT JOIN preserva todas as linhas da tabela à esquerda, preenchendo com NULL os campos da direita quando não há correspondência.',
  },
  {
    id: 'th-16',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Por que um índice em uma coluna não é "grátis" — qual o principal custo de adicionar índices em excesso?',
    options: [
      'Índices não têm custo nenhum',
      'Cada índice precisa ser atualizado a cada escrita (INSERT/UPDATE/DELETE), tornando escritas mais lentas e ocupando mais espaço em disco',
      'Índices tornam todas as leituras mais lentas',
      'Só é possível ter um índice por tabela',
    ],
    correctIndex: 1,
    explanation: 'Índices aceleram leitura mas têm custo de manutenção em toda escrita, além de espaço de armazenamento — o trade-off precisa ser avaliado por padrão de uso real.',
  },
  // ===== Git / DevOps =====
  {
    id: 'th-17',
    track: ['frontend', 'backend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Qual a diferença prática entre `git merge` e `git rebase` ao integrar uma branch?',
    options: [
      'Não há diferença, produzem o mesmo histórico',
      'merge cria um commit de junção preservando o histórico original; rebase reescreve os commits da branch para aparecerem sequencialmente após a outra branch',
      'rebase é usado só para deletar branches',
      'merge não funciona com mais de duas branches',
    ],
    correctIndex: 1,
    explanation: 'merge preserva a história real (incluindo um commit de merge); rebase "reaplica" os commits para um histórico linear, reescrevendo hashes de commit no processo.',
  },
  {
    id: 'th-18',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Qual o benefício principal de um multi-stage build no Dockerfile?',
    options: [
      'Permite usar duas linguagens simultaneamente no mesmo container',
      'Gera uma imagem final menor, descartando ferramentas de build que só eram necessárias para compilar',
      'Torna o build propositalmente mais lento por segurança',
      'É obrigatório em qualquer Dockerfile moderno',
    ],
    correctIndex: 1,
    explanation: 'O estágio final copia só os artefatos já compilados, sem as dependências de build, resultando numa imagem de produção significativamente menor.',
  },
  // ===== Atualidades / IA em desenvolvimento =====
  {
    id: 'th-19',
    track: ['frontend', 'backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Ao usar um assistente de IA (como Copilot ou similares) para gerar código, qual é a prática mais responsável?',
    options: [
      'Aceitar todo código sugerido sem revisão, para ganhar velocidade',
      'Revisar e entender o código gerado antes de aceitar, tratando-o como sugestão de um colega júnior — útil, mas que precisa de revisão',
      'Nunca usar essas ferramentas em hipótese alguma',
      'Usar apenas para escrever comentários, nunca lógica',
    ],
    correctIndex: 1,
    explanation: 'Assistentes de IA aceleram bastante o desenvolvimento, mas podem gerar código com bugs sutis, vulnerabilidades ou que não segue os padrões do projeto — revisão crítica continua sendo responsabilidade do desenvolvedor.',
  },
  {
    id: 'th-20',
    track: ['frontend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'O que é Core Web Vitals, métrica que o Google usa para avaliar experiência de página?',
    options: [
      'Um framework de testes unitários',
      'Um conjunto de métricas de performance real percebida pelo usuário (velocidade de carregamento, estabilidade visual, responsividade a interações)',
      'Uma biblioteca de componentes do React',
      'Um tipo de banco de dados NoSQL',
    ],
    correctIndex: 1,
    explanation: 'Core Web Vitals mede aspectos como LCP (carregamento do conteúdo principal), CLS (estabilidade visual) e INP (responsividade), influenciando inclusive ranqueamento em buscas.',
  },
  {
    id: 'th-21',
    track: ['backend', 'fullstack'],
    level: ['senior'],
    prompt: 'Em times que adotam observabilidade moderna, qual a diferença entre métricas, logs e traces?',
    options: [
      'São a mesma coisa com nomes diferentes',
      'Métricas são números agregados ao longo do tempo; logs são eventos discretos com contexto; traces seguem uma requisição através de múltiplos serviços',
      'Logs substituem completamente métricas e traces',
      'Traces só existem em aplicações frontend',
    ],
    correctIndex: 1,
    explanation: 'Essas três pilares da observabilidade respondem perguntas diferentes: métricas mostram tendências, logs mostram detalhes de eventos específicos, traces mostram o caminho completo de uma requisição entre serviços.',
  },
  {
    id: 'th-22',
    track: ['frontend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Qual a vantagem de usar TypeScript em vez de JavaScript puro num projeto em equipe?',
    options: [
      'TypeScript executa mais rápido no navegador que JavaScript',
      'A checagem de tipos em tempo de compilação pega erros antes da execução, e melhora a experiência de autocompletar/refatorar em times grandes',
      'TypeScript elimina completamente a necessidade de testes',
      'Navegadores executam TypeScript nativamente',
    ],
    correctIndex: 1,
    explanation: 'TypeScript é transpilado para JavaScript — a vantagem não é performance em runtime, é detectar erros de tipo durante o desenvolvimento, antes que cheguem em produção.',
  },
  {
    id: 'th-23',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'O que motiva uma equipe a adotar arquitetura serverless (como AWS Lambda) para certas funcionalidades?',
    options: [
      'É sempre mais barato que servidores tradicionais em qualquer escala',
      'Para cargas esporádicas ou imprevisíveis, paga-se só pelo tempo de execução real, sem manter infraestrutura ociosa',
      'Serverless elimina a necessidade de qualquer código',
      'É a única forma de usar Node.js na nuvem',
    ],
    correctIndex: 1,
    explanation: 'Serverless é vantajoso para cargas variáveis/esporádicas. Para cargas constantes e previsíveis, servidores tradicionais (ou containers) costumam ser mais econômicos.',
  },
  {
    id: 'th-24',
    track: ['frontend', 'backend', 'fullstack'],
    level: ['junior', 'pleno', 'senior'],
    prompt: 'O que significa "dívida técnica" no contexto de desenvolvimento de software?',
    options: [
      'Dinheiro que a empresa deve a fornecedores de tecnologia',
      'O custo futuro implícito de escolhas rápidas/simplificadas feitas no presente, que precisarão ser revistas ou refatoradas depois',
      'Um tipo de erro de compilação',
      'A quantidade de bugs abertos no sistema de tickets',
    ],
    correctIndex: 1,
    explanation: 'Dívida técnica é a diferença entre a solução "rápida o suficiente para agora" e a solução ideal — ela se acumula e, sem ser paga (refatorada), torna mudanças futuras progressivamente mais lentas e arriscadas.',
  },
  {
    id: 'th-25',
    track: ['security', 'backend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Por que usar query parametrizada em vez de concatenar string previne SQL Injection?',
    options: [
      'Porque é mais rápido de executar',
      'Porque o banco trata o valor do parâmetro como dado puro, nunca como parte do comando SQL — não importa o que o usuário digite',
      'Porque queries parametrizadas não usam o banco de dados',
      'Não há diferença real de segurança',
    ],
    correctIndex: 1,
    explanation: 'A separação entre comando SQL e dados é o que impede um valor malicioso de "virar" parte do comando — o banco nunca interpreta o conteúdo do parâmetro como SQL executável.',
  },
  {
    id: 'th-26',
    track: ['security', 'frontend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Por que usar salt junto com hash de senha, em vez de hash puro?',
    options: [
      'Salt deixa a senha mais fácil de digitar',
      'Salt garante que senhas iguais gerem hashes diferentes, neutralizando ataques com tabelas pré-calculadas (rainbow tables)',
      'Salt substitui completamente a necessidade de hash',
      'Não há diferença prática',
    ],
    correctIndex: 1,
    explanation: 'Sem salt, duas pessoas com a mesma senha teriam o mesmo hash — uma rainbow table descobre ambas de uma vez. Salt único por usuário elimina esse atalho.',
  },
  {
    id: 'th-27',
    track: ['security', 'backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Qual o propósito de um CSRF token num formulário?',
    options: [
      'Acelerar o envio do formulário',
      'Garantir que a requisição partiu do seu próprio site, e não foi forjada por outro site usando a sessão já autenticada da vítima',
      'Criptografar os dados do formulário',
      'Validar o formato de email',
    ],
    correctIndex: 1,
    explanation: 'Um site malicioso não conhece o token gerado pelo servidor legítimo — sem ele (ou com ele errado), a requisição forjada é rejeitada.',
  },
  {
    id: 'th-28',
    track: ['security', 'fullstack'],
    level: ['senior'],
    prompt: 'O que caracteriza um "controle de acesso quebrado" (broken access control), item recorrente do OWASP Top 10?',
    options: [
      'O sistema não tem nenhum tipo de login',
      'Um usuário autenticado consegue acessar ou modificar dados de outro usuário, geralmente só trocando um ID na URL, porque a aplicação não verifica posse do recurso',
      'O servidor está fora do ar',
      'O banco de dados está corrompido',
    ],
    correctIndex: 1,
    explanation: 'Autenticação (saber quem é) é diferente de autorização (poder fazer aquilo especificamente) — checar só a primeira e esquecer a segunda é a causa mais comum desse problema.',
  },
  {
    id: 'th-29',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Por que Python usa indentação como parte da sintaxe, em vez de chaves como JavaScript/Java?',
    options: [
      'É uma limitação técnica da linguagem',
      'Foi uma escolha de design para forçar código visualmente organizado e legível, eliminando ambiguidade sobre onde um bloco começa/termina',
      'Python não suporta blocos de código',
      'Apenas para diferenciar visualmente de outras linguagens',
    ],
    correctIndex: 1,
    explanation: 'A indentação obrigatória é uma escolha deliberada de design da linguagem, que elimina a possibilidade de blocos malformados ou mal-indentados que ainda compilam, comum em linguagens com chaves.',
  },
  {
    id: 'th-30',
    track: ['backend', 'fullstack'],
    level: ['pleno'],
    prompt: 'Qual a diferença entre uma lista e uma tupla em Python?',
    options: [
      'Não há diferença real',
      'Lista é mutável; tupla é imutável — uma vez criada, seus valores não podem ser alterados',
      'Tupla só aceita números',
      'Lista é mais rápida em qualquer operação',
    ],
    correctIndex: 1,
    explanation: 'A imutabilidade da tupla é a diferença central — útil para representar dados que não deveriam mudar, como coordenadas ou configurações fixas.',
  },
  {
    id: 'th-31',
    track: ['backend', 'fullstack'],
    level: ['senior'],
    prompt: 'Por que uma goroutine em Go é consideravelmente mais "barata" que uma thread tradicional do sistema operacional?',
    options: [
      'Goroutines não fazem nada de útil',
      'Goroutines consomem muito menos memória cada (alguns KB vs MB de uma thread), permitindo rodar centenas de milhares simultaneamente',
      'Goroutines são threads renomeadas, sem diferença real',
      'Goroutines só funcionam em máquinas com múltiplos núcleos',
    ],
    correctIndex: 1,
    explanation: 'O runtime do Go gerencia goroutines de forma muito mais leve que o sistema operacional gerencia threads — essa eficiência é central à proposta de concorrência da linguagem.',
  },
  {
    id: 'th-32',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Como uma função em Go tipicamente sinaliza que algo deu errado, já que a linguagem não tem try/catch tradicional?',
    options: [
      'Lançando uma exceção com throw',
      'Retornando um valor de erro explícito, geralmente como o último valor de retorno, que o código chamador deve checar',
      'Go não tem como sinalizar erros',
      'Travando o programa imediatamente',
    ],
    correctIndex: 1,
    explanation: 'Go trata erros como valores normais de retorno — essa visibilidade explícita é uma escolha de design para deixar claro, na leitura do código, onde cada erro pode ocorrer.',
  },
  {
    id: 'th-33',
    track: ['backend', 'fullstack'],
    level: ['pleno'],
    prompt: 'Qual a diferença fundamental entre como SQL e MongoDB guardam dados?',
    options: [
      'Não há diferença real',
      'SQL usa tabelas com colunas fixas; MongoDB usa documentos flexíveis, que podem variar de estrutura entre si',
      'MongoDB só funciona com números',
      'SQL é sempre mais rápido em qualquer cenário',
    ],
    correctIndex: 1,
    explanation: 'A flexibilidade de schema do MongoDB é a diferença central — útil quando os dados não são uniformes, mas custa algumas garantias fortes que SQL oferece nativamente.',
  },
  {
    id: 'th-34',
    track: ['backend', 'fullstack'],
    level: ['pleno', 'senior'],
    prompt: 'Por que Redis é usado como cache, em vez de banco de dados principal, na maioria dos sistemas?',
    options: [
      'Redis não consegue guardar dados de verdade',
      'Redis guarda dados na memória RAM (extremamente rápido), mas sem configuração extra de persistência, dados podem se perder em um reinício — por isso fica na frente de um banco mais durável',
      'Redis só funciona com números',
      'Redis é mais lento que bancos tradicionais',
    ],
    correctIndex: 1,
    explanation: 'A velocidade do Redis vem do trade-off de durabilidade — ele é ideal para dados que podem ser recalculados/buscados de novo, não para ser a única fonte de verdade.',
  },
  {
    id: 'th-35',
    track: ['security', 'backend', 'fullstack'],
    level: ['junior', 'pleno'],
    prompt: 'Qual o propósito de rate limiting numa rota de login?',
    options: [
      'Tornar o login mais rápido',
      'Limitar quantas tentativas uma mesma origem pode fazer num intervalo de tempo, tornando ataques de força bruta impraticáveis',
      'Validar o formato do email',
      'Criptografar a senha automaticamente',
    ],
    correctIndex: 1,
    explanation: 'Sem rate limiting, um atacante pode testar milhares de combinações de senha por segundo de forma automatizada — limitar tentativas por período torna isso inviável.',
  },
];
